[package]
name = "c-lib"
version = "0.1.0"
authors = ["ppmag <mybestexpert@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nitroattest"
crate-type = ["cdylib", "staticlib"]   

[dependencies]
